

import os


def get_secret(name: str, default: str = "") -> str:

    try:
        import streamlit as st
        if name in st.secrets:
            return st.secrets[name]
    except Exception:
        pass  
    return os.environ.get(name, default)


LLM_PROVIDER = get_secret("LLM_PROVIDER", "gemini").lower()

OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
OPENAI_MODEL = get_secret("OPENAI_MODEL", "gpt-4o-mini")

ANTHROPIC_API_KEY = get_secret("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = get_secret("ANTHROPIC_MODEL", "claude-3-5-sonnet-latest")

GEMINI_API_KEY = get_secret("GEMINI_API_KEY", "")
GEMINI_MODEL = get_secret("GEMINI_MODEL", "gemini-2.5-flash")

LLM_TEMPERATURE = 0.2
LLM_MAX_TOKENS = 600
LLM_TIMEOUT_SECONDS = 60

KNOWLEDGE_BASE_DIR = os.path.join(os.path.dirname(__file__), "knowledge_base")
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
CHUNK_SIZE = 500          # characters per chunk
CHUNK_OVERLAP = 80
TOP_K_RESULTS = 4
VECTOR_INDEX_PATH = os.path.join(os.path.dirname(__file__), "data", "vector_index")

NON_MEDICAL_REFUSAL_MESSAGE = (
    "I'm a medical-assistant chatbot and can only help with health, disease, "
    "symptom, or medication related questions. Please ask something related "
    "to health or medicine."
)

MEDICAL_DISCLAIMER = (
    "⚠️ This tool provides informational suggestions generated by machine "
    "learning models and an AI assistant. It is **not** a substitute for "
    "professional medical diagnosis or treatment. Please consult a licensed "
    "doctor before making any health decisions."
)


ENABLE_WEB_SEARCH = get_secret("ENABLE_WEB_SEARCH", "true").lower() == "true"
PUBMED_MAX_RESULTS = 3
MEDLINEPLUS_MAX_RESULTS = 3
WEB_REQUEST_TIMEOUT = 15

TAVILY_API_KEY = get_secret("TAVILY_API_KEY", "")

OVERPASS_URL = "https://overpass-api.de/api/interpreter"
NOMINATIM_USER_AGENT = "medical-rag-streamlit-app"
DEFAULT_SEARCH_RADIUS_METERS = 5000
